### ISSUE TITLE
cannot import name 'feature_selection' from 'selection'

### ISSUE THREAD

**Issue by MonikaLamba** [tlatkowski/deep-learning-gene-expression#3]

**Comment by MonikaLamba** [comment]
Not able to resolve this issue

**Comment by tlatkowski** [comment]
Hi @MonikaLamba, could you provide more details ? Your OS, how do you run the code?

**Comment by MonikaLamba** [comment]
Hi Sir
Actually I tried to run the code in juypter notebook and today on spyder.
I am receiving the same message on both that is 

from selection import feature_selection
Traceback (most recent call last):

  File "<ipython-input-4-1c2079b35ef5>", line 1, in <module>
    from selection import feature_selection

ImportError: cannot import name 'feature_selection' from 'selection' (C:\ProgramData\Anaconda3\lib\site-packages\selection\__init__.py)

**Comment by MonikaLamba** [comment]
sir, i am attaching the screenshot of the output.
[error.pdf](https://github.com/tlatkowski/deep-learning-gene-expression/files/3608641/error.pdf)
i am running this on window 10

**Comment by MonikaLamba** [comment]
the file named init__.py is empty in the folder you have uploaded on git hub

**Comment by MonikaLamba** [comment]
\Desktop\deep-learning-gene-expression-master\selection\__init__.py in <module>
      1 from weblib.const import NULL  # noqa
      2 
----> 3 from selection.base import Selector, SelectorList, RexResultList  # noqa
      4 from selection.backend import XpathSelector  # noqa
      5 

ModuleNotFoundError: No module named 'selection.base'

plus this selection.base module is not defined in file

**Comment by tlatkowski** [comment]
Hi @MonikaLamba , thanks for the details. It looks like this issue is related to your OS. Unfortunately, i haven't tested the pipeline on Windows but i'm currently preparing Google Colaboratory notebook for this pipeline,  so as a result you will be able to run it no matter your operating system.

**Comment by tlatkowski** [comment]
Hi @MonikaLamba ,

I have added Google Colab you can use it to run the pipeline.

[https://github.com/tlatkowski/deep-learning-gene-expression/blob/master/colab/deep_learning_feature_selection.ipynb](url)

**Comment by MonikaLamba** [comment]
Thank you so much sir
